name: Reveal.js CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t revealjs:latest .

      - name: Install Latest Trivy on Ubuntu
        run: scripts/github-workflow-scripts/install_trivy.sh

      - name: Run Trivy Security Scan
        id: trivy
        run: |
          python3 scripts/run_trivy_scan.py || echo "TRIVY_FAILED=true" >> $GITHUB_ENV
      
      
      - name: Fail if Trivy Found Issues
        if: env.TRIVY_FAILED == 'true'
        run: exit 1  # 🚨 Fail the job after uploading
      