---

name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.5

      - name: Install and run TFLint and Generate and upload Report
        id: tflint
        run: python3 scripts/run_tflint_check.py || echo "TFLINT_FAILED=true" >> $GITHUB_ENV

      - name: Fail if TFLint Found Issues
        if: env.TFLINT_FAILED == 'true'
        run: exit 1  # 🚨 Fail the job after uploading

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
