---

name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.5

      - name: Install and run TFLint and Generate Report
        run: scripts/run_tflint_check.sh

      - name: Commit and Push TFLint Report
        run: |
          # If the report does not exist, create an empty one
          if [[ ! -f tflint_report.md ]]; then
            echo "# TFLint Report" > tflint_report.md
            echo "Generated on $(date)" >> tflint_report.md
            echo "" >> tflint_report.md
            echo "No issues found." >> tflint_report.md
          fi

          # Stop if no changes were made (prevents unnecessary commits)
          if git diff --quiet tflint_report.md; then
            echo "No changes detected in TFLint report. Skipping commit."
            exit 0
          fi

          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

          # Only add TFLint report, prevent other files from being committed
          git add tflint_report.md
          git commit -m "chore(ci): update TFLint report [skip ci]"
          git push
  
  

      - name: Fail Job if TFLint Found Issues
        if: always()
        run: |
          if [[ "$TFLINT_EXIT_CODE" -ne 0 ]]; then
            echo "TFLint found issues. Failing job."
            exit 1
          fi

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
